Mvc4InSys/Controllers/UserLogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc4InSys.Models;
using PagedList;

namespace Mvc4InSys.Controllers
{
    public class UserLogController : Controller
    {
        private NewInSysEntities db = new NewInSysEntities();

        //
        // GET: /UserLog/

        public ActionResult Index(string sSearchUserID, string currentFilter, string sListDatabaseName, int? Page)
        {
            ViewBag.sSearchUserID = sSearchUserID;

            ViewBag.sListDatabaseName = sListDatabaseName;

            var listTbAuditTrail = from tempAuditTrail in db.tbAuditTrail
                                   select tempAuditTrail;

            if (!String.IsNullOrEmpty(sSearchUserID))
            {
                listTbAuditTrail = listTbAuditTrail
                     .Where(s => s.UserId.Contains(sSearchUserID));
            }
            if (!String.IsNullOrEmpty(sListDatabaseName))
            {
                listTbAuditTrail = listTbAuditTrail
                     .Where(s => s.DatabaseName.Contains(sListDatabaseName));
            }


            listTbAuditTrail = listTbAuditTrail.OrderByDescending(o => o.LogID);

                int pageSize = 20;
                int pageNumber = (Page ?? 1);
                if (Request.IsAuthenticated)
                {
                        return View(listTbAuditTrail.ToPagedList(pageNumber, pageSize));
                }
                else
                { 
                    return RedirectToAction("Login","Login");
                }
        }

        //
        // GET: /UserLog/Details/5

        public ActionResult Details(long id = 0)
        {
            tbAuditTrail tbaudittrail = db.tbAuditTrail.Find(id);
            if (tbaudittrail == null)
            {
                return HttpNotFound();
            }
            return View(tbaudittrail);
        }

        //
        // GET: /UserLog/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /UserLog/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tbAuditTrail tbaudittrail)
        {
            if (ModelState.IsValid)
            {
                db.tbAuditTrail.Add(tbaudittrail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbaudittrail);
        }

        //
        // GET: /UserLog/Edit/5

        public ActionResult Edit(long id = 0)
        {
            tbAuditTrail tbaudittrail = db.tbAuditTrail.Find(id);
            if (tbaudittrail == null)
            {
                return HttpNotFound();
            }
            return View(tbaudittrail);
        }

        //
        // POST: /UserLog/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(tbAuditTrail tbaudittrail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbaudittrail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbaudittrail);
        }

        //
        // GET: /UserLog/Delete/5

        public ActionResult Delete(long id = 0)
        {
            tbAuditTrail tbaudittrail = db.tbAuditTrail.Find(id);
            if (tbaudittrail == null)
            {
                return HttpNotFound();
            }
            return View(tbaudittrail);
        }

        //
        // POST: /UserLog/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            tbAuditTrail tbaudittrail = db.tbAuditTrail.Find(id);
            db.tbAuditTrail.Remove(tbaudittrail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Mvc4InSys/Views/UserLog/Create.cshtml
@model Mvc4InSys.Models.tbAuditTrail

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>tbAuditTrail</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogID)
            @Html.ValidationMessageFor(model => model.LogID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AccessTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AccessTime)
            @Html.ValidationMessageFor(model => model.AccessTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DatabaseName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DatabaseName)
            @Html.ValidationMessageFor(model => model.DatabaseName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ActionDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ActionDescription)
            @Html.ValidationMessageFor(model => model.ActionDescription)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mvc4InSys/Views/UserLog/Delete.cshtml
@model Mvc4InSys.Models.tbAuditTrail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>tbAuditTrail</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AccessTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AccessTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DatabaseName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DatabaseName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActionDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActionDescription)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Mvc4InSys/Views/UserLog/Details.cshtml
@model Mvc4InSys.Models.tbAuditTrail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>tbAuditTrail</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AccessTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AccessTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DatabaseName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DatabaseName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActionDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActionDescription)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Mvc4InSys/Views/UserLog/Edit.cshtml
@model Mvc4InSys.Models.tbAuditTrail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>tbAuditTrail</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogID)
            @Html.ValidationMessageFor(model => model.LogID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AccessTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AccessTime)
            @Html.ValidationMessageFor(model => model.AccessTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DatabaseName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DatabaseName)
            @Html.ValidationMessageFor(model => model.DatabaseName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ActionDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ActionDescription)
            @Html.ValidationMessageFor(model => model.ActionDescription)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mvc4InSys/Views/UserLog/Index.cshtml
@*@model IEnumerable<Mvc4InSys.Models.tbAuditTrail>*@
@model PagedList.IPagedList<Mvc4InSys.Models.tbAuditTrail>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Audit Trail</h2>

@using (Html.BeginForm("Index", "UserLog", FormMethod.Get))
{
    <p>
        User ID &nbsp;&nbsp; : @Html.TextBox("sSearchUserID", ViewBag.sSearchUserID as string)<br />
        Database : @Html.TextBox("sListDatabaseName", ViewBag.sListDatabaseName as string)<br />
        <input type="submit" value="Search" /></p>
}


<table>
    @{ if (@Model.PageCount!=0)
       {
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.LogID)*@
            LogID
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.AccessTime)*@
            AccessTime
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.UserId)*@
            UserId
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.DatabaseName)*@
            DatabaseName
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.ActionDescription)*@
            ActionDescription
        </th>
    </tr>
    }
    else
    {
       <h3>No record found</h3>
       }
    }
@{
    int iIndex=1;
    string sClass;

    if(Model!=null)
    {
        foreach (var item in Model) {
            if (iIndex % 2 != 0)
            {
                sClass = "tdganjil";
            }
            else
            {
                sClass = "tdgenap";
            }
            <tr>
                <td class="@sClass">
                    @Html.DisplayFor(modelItem => item.LogID)
                </td>
                <td class="@sClass">
                    @Html.DisplayFor(modelItem => item.AccessTime)
                </td>
                <td class="@sClass">
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td class="@sClass">
                    @Html.DisplayFor(modelItem => item.DatabaseName)
                </td>
                <td class="@sClass">
                    @Html.DisplayFor(modelItem => item.ActionDescription)
                </td>
               
            </tr>
            iIndex++;
        }
    }   
}
</table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", 
    new { page,sSearchUserID = ViewBag.sSearchUserID, sListDatabaseName = ViewBag.sListDatabaseName}))